sudo: false
dist: xenial
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"

# Install the codecov pip dependency
install:
  - pipenv install 

# Run the unit test
script:
  - pipenv run python -m pytest

