sudo: false
dist: xenial
language: python
python: 
  - "3.7"
  - "3.8"
  - "nightly"

# Install the codecov pip dependency
install:
  - pipenv install 

# Run the unit test
script:
  - pipenv run python -m pytest

