version: 1
update_configs:
  - package_manager: "python"
    directory: "/"
    update_schedule: "daily"
    automerged_updates:
      - match:
          dependency_name: "*"
          update_type: "semver:minor"
