name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup Poetry
      - uses: Gr1N/setup-poetry@v2
        with:
          python_version: ${{ matrix.python-version }}

      - name: Tests
        run: poetry run python -m pytest
